### ISSUE TITLE
Key function: MAGeCK test module

### ISSUE THREAD

**Issue by Goosang-Yu** [Goosang-Yu/genet#32]
Input 
- Output of mageck.count

Option parameters
- control: Select column (data) for control group in screening
- test: Select column (data) for test group in screening

Source code (original MAGeCK):
https://bitbucket.org/liulab/mageck/src/master/rra/src/
-> This is C++ code, is there python source?

**Comment by ntfargo** [comment]
There is no python code as i see but you can use python wrapper around C++ code acts as a bridge, allowing Python programs to interact with C++ functions and classes seamlessly. This can bit complex but may work.
