### ISSUE TITLE
Testing the most recent versions of libraries

### ISSUE THREAD

**Issue by ntfargo** [Goosang-Yu/genet#35]
Awaiting verification at [ntfargo-dev](https://github.com/Goosang-Yu/genet/tree/ntfargo-dev) branch.

The code requires a thorough review to ensure its quality and functionality. Some functions may not work!

**Comment by Goosang-Yu** [comment]
It seems to me that there are three main components based on my understanding:

1. Applying it for PyTorch 2 installation.
2. Updating the ReadMe.
3. The Makefile.

Should I primarily focus on these three?

**Comment by ntfargo** [comment]
I writed this issue for myself actually :D I created the makefile (mingw32) to simplify the first installation and avoid dealing with that separately. Later, I would like to create a more understandable documentation as well. As I said on Slack, I want to make the genet compatible with the latest environment. If you have an idea, please share it.
