### ISSUE TITLE
Some comments about installation on macos M2 Pro

### ISSUE THREAD

**Issue by francoiskroll** [Goosang-Yu/genet#86]
In case it's helpful for the authors or future users, here is what worked on my M2 Pro macbook after a few trials:

```
conda create -n genet
conda activate genet
```

`viennarna` (a necessary dependency) does not have an arm64 install on conda at the time of writing ([see](https://anaconda.org/bioconda/viennarna)), so we make the environment x64 with:

```
conda config --env --set subdir osx-64
```
Now to install dependencies (beware, do _not_ be impatient and directly create the conda environment with `conda create -n genet python=3.8` as recommended as that would install an arm64 version of python and create issues later).

```
conda install python=3.8
conda install conda-forge::tensorflow
pip install genet

# here, tutorial says pip install torch==1.11.0+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
# but that did not work for me
# I ran below and everything seems OK (although I have not used the package extensively yet)
pip install torch==1.11.0

conda install bioconda::viennarna
```

As first job, run:

```
from genet.predict import DeepPrime

seq_wt   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGAAGAACTATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'
seq_ed   = 'ATGACAATAAAAGACAACACCCTTGCCTTGTGGAGTTTTCAAAGCTCCCAGAAACTGAGACGAACTATAACCTGCAAATGTCAACTGAAACCTTAAAGTGAGTATTTAATTGAGCTGAAGT'

pegrna = DeepPrime('SampleName', seq_wt, seq_ed, edit_type='sub', edit_len=1)

pe2max_output = pegrna.predict(pe_system='PE2max', cell_type='HEK293T')
```

This should download model files (see #84) and test the install.

**Comment by Goosang-Yu** [comment]
Thanks for sharing the detailed instructions for installing Genet on M2 Pro! 
Honestly, I haven't had much experience using MacOS, so I haven't been able to test it extensively. It's been really helpful.

Upon closer inspection, it seems that versions of Python below 3.8 are not supported on Apple Silicon. 
That might have been part of the problem. [Link to the issue](https://github.com/conda/conda/issues/12206)

Do you think there would be no problem installing Python when creating a virtual environment with Python 3.9 or 3.10?

Also, I noticed that there might have been an issue with the [installation instructions on the DeepPrime web version](https://deepcrispr.info/DeepPrime/page/help_genet), so I've made some corrections. 

Thanks again for sharing such valuable information!

**Comment by francoiskroll** [comment]
No problem, glad I could help.

**Comment by Goosang-Yu** [comment]
From genet >= 0.15.0, we don't need to install torch and viannarna seperately! 
Also, genet now import torch >= 2.0 🎉
