### ISSUE TITLE
Different outputs webtool vs python package?

### ISSUE THREAD

**Issue by francoiskroll** [Goosang-Yu/genet#88]
Sorry about the many questions!

Let's say I try exactly the same input with both the webtool & the Python package.

### Webtool

<img width="573" alt="Screenshot 2024-04-22 at 17 12 01" src="https://github.com/Goosang-Yu/genet/assets/26249001/6d0813a7-39c2-4312-995d-24e52aad7372">

<img width="1095" alt="Screenshot 2024-04-22 at 17 12 31" src="https://github.com/Goosang-Yu/genet/assets/26249001/9133b8f6-1d20-4747-b22d-8472c799a4ba">

Top predicted pegRNA is
* gN19 = `GCTCGGCGAGCGACTACTGT`
* sPBS_RTSeq = `AGCGACTACTGTAGGTCGTCATGGGGCCGAA`
* DeepPrime_score = 16.006807

### Python package

```
pegrna = DeepPrime('test',
                   'TTTTGGGTTTTATCCTACAGCCCGTCATCGGCTCGGCGAGCGACTACTGTAGGTCGTCATAAGGCCGAAGGAGACCGTACATACTCTTACTGGGGATTCTGATGTTAGTGGGCATGACTTT',
                   'TTTTGGGTTTTATCCTACAGCCCGTCATCGGCTCGGCGAGCGACTACTGTAGGTCGTCATGGGGCCGAAGGAGACCGTACATACTCTTACTGGGGATTCTGATGTTAGTGGGCATGACTTT',
                   edit_type='sub',
                   edit_len=2)

pe2_output = pegrna.predict(pe_system='PE2', cell_type='HEK293T')
```

Top predicted pegRNA is
* gN19 = `GCTCGGCGAGCGACTACTGT`
* sPBS_RTSeq = `TTCGGCCCCATGACGACCTACAGTAGTCGCT` (which is exactly reverse-complement of webtool output)
* PE2_score = 15.269821167

I guess the top-predicted pegRNA is the same in both cases, but the score is slightly different? Anything I should worry about?

**Comment by Goosang-Yu** [comment]
The response of issue #45 might be helpful.

In short, if you have to choose one, I recommend using GenET. GenET is actively maintained, with discovered bugs being fixed, and it receives regular updates.

**Comment by francoiskroll** [comment]
Yes that perfectly answers my question. Sorry I hadn't seen it!
