### ISSUE TITLE
Meaning of iteration on sForTm3 in `genet.predict.PrimeEditor.PEFeatureExtraction.determine_Tm`

### ISSUE THREAD

**Issue by DENGARDEN** [Goosang-Yu/genet#96]
yHi, I would like to ask the authors about the explanation of the method, genet.predict.PrimeEditor.PEFeatureExtraction.determine_Tm`

Why is there iteration for sForTm3 and storing the calculated Tm_NN value in a list? The `list_fTm3` is not used anymore other than here, and fTm3 is always assigned as the Tm_NN of the last sSeq1 and sSeq2. 

Please let me know the hidden mechanism behind this if this is expected.
Many thanks for considering my request.

``` [Python]
# genet.predict.PrimeEditor.py
## Tm3 DNA/DNA mm1 ##
if not sForTm3:
    fTm3 = 0
    fTm5 = 0

else:
    list_fTm3 = []
    for sSeq1, sSeq2 in zip(sForTm3[0], sForTm3[1]):
        try:
            fTm3 = mt.Tm_NN(seq=sSeq1, c_seq=sSeq2, nn_table=mt.DNA_NN3)
        except ValueError:
            continue

        list_fTm3.append(fTm3)
    # loop END: sSeq1, sSeq2

```

**Comment by Goosang-Yu** [comment]
Hi,

Yes, it is indeed an unnecessary list. It seems to be leftover code from the development process, possibly created for another feature. We can remove it later.

Thank you!
